
package Vista;

import Recursos.Metodos_generales;
import Modelo.Login;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author NN
 */
public class MenuAdmin_JFrame extends javax.swing.JFrame {
    
    private static MenuAdmin_JFrame menu;
    /**
     * Creates new form MenuEmpl_JFrame
     */
     private MenuAdmin_JFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_admin.setText("Administrador: "+Login.getNombre());
    }
     
     public static MenuAdmin_JFrame getMenu(){
         if(menu==null){
             menu= new MenuAdmin_JFrame();
         }
         return menu;
     }
    
    public Image getIconImage(){
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.jpg"));
        return retvalue;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_datos = new javax.swing.JButton();
        btn_inventario = new javax.swing.JButton();
        btn_tools = new javax.swing.JButton();
        btn_notas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Frase = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        lbl_admin = new javax.swing.JLabel();
        btn_configuracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 220, 62));

        btn_datos.setBackground(new java.awt.Color(255, 116, 1));
        btn_datos.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        btn_datos.setForeground(new java.awt.Color(255, 255, 255));
        btn_datos.setText("Gestión de Datos");
        btn_datos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_datos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datosActionPerformed(evt);
            }
        });

        btn_inventario.setBackground(new java.awt.Color(255, 116, 1));
        btn_inventario.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        btn_inventario.setForeground(new java.awt.Color(255, 255, 255));
        btn_inventario.setText("Inventario");
        btn_inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });

        btn_tools.setBackground(new java.awt.Color(255, 116, 1));
        btn_tools.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        btn_tools.setForeground(new java.awt.Color(255, 255, 255));
        btn_tools.setText("Herramientas ");
        btn_tools.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tools.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toolsActionPerformed(evt);
            }
        });

        btn_notas.setBackground(new java.awt.Color(255, 116, 1));
        btn_notas.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        btn_notas.setForeground(new java.awt.Color(255, 255, 255));
        btn_notas.setText("Notas y ventas");
        btn_notas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_notas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notasActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>YerAlitas <hr/></html>");

        jLabel_Frase.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel_Frase.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Frase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Frase.setText("\"Sabor inigualable\"\n");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loguito.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        btn_exit.setBackground(new java.awt.Color(0, 220, 62));
        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        btn_exit.setToolTipText("Cerrar sesión");
        btn_exit.setBorder(null);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        lbl_admin.setBackground(new java.awt.Color(255, 255, 255));
        lbl_admin.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lbl_admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_admin.setOpaque(true);

        btn_configuracion.setBackground(new java.awt.Color(0, 220, 62));
        btn_configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil.png"))); // NOI18N
        btn_configuracion.setBorder(null);
        btn_configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel_Frase, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(232, 232, 232)
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tools, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_exit)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_configuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Frase))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tools, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        Inicio_JFrame inicio= new Inicio_JFrame();
        inicio.show();
        this.dispose();

    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_notasActionPerformed
        // TODO add your handling code here:
        NotVent_JFrame notas= new NotVent_JFrame();
        notas.show();
        this.dispose();

    }//GEN-LAST:event_btn_notasActionPerformed

    private void btn_toolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toolsActionPerformed
        // TODO add your handling code here:
        Herramientas_JFrame.getHerramienta();
    }//GEN-LAST:event_btn_toolsActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        // TODO add your handling code here:
        Inventario_JFrame inventario= new Inventario_JFrame();
        inventario.show();
        this.dispose();

    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datosActionPerformed
        // TODO add your handling code here:
        Metodos_generales.Inventario();
        this.dispose();

    }//GEN-LAST:event_btn_datosActionPerformed

    private void btn_configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionActionPerformed
        // TODO add your handling code here:
        ConfigAdmin_JFrame confi= new ConfigAdmin_JFrame();
        confi.show();
        this.dispose();
    }//GEN-LAST:event_btn_configuracionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JButton btn_datos;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_inventario;
    private javax.swing.JButton btn_notas;
    private javax.swing.JButton btn_tools;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Frase;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_admin;
    // End of variables declaration//GEN-END:variables
}
